# Generated by Django 5.1.7 on 2025-03-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_time',
            new_name='date_and_time',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='email_address',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='order',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='crypto_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='fiat_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
